FROM node:22-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV CI=true
RUN corepack enable

WORKDIR /app

FROM base AS builder

ENV PNPM_CONFIG_ONLY_BUILT_DEPENDENCIES=none

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml* turbo.json ./
COPY apps/api/package.json ./apps/api/
COPY apps/web/package.json ./apps/web/
COPY packages/schemas/package.json ./packages/schemas/

RUN pnpm install --no-frozen-lockfile 

COPY . .

RUN pnpm exec turbo run build --filter=api
RUN pnpm install --prod --no-frozen-lockfile --ignore-scripts


FROM base AS runner
ENV NODE_ENV=development

WORKDIR /app

COPY --from=builder --chown=node:node /app/node_modules ./node_modules
COPY --from=builder --chown=node:node /app/apps/api/node_modules ./apps/api/node_modules
COPY --from=builder --chown=node:node /app/packages/schemas/ ./packages/schemas
COPY --from=builder --chown=node:node /app/apps/api/dist ./apps/api/dist

USER node

EXPOSE 3000

CMD ["node", "apps/api/dist/main.js"]
